Repository NicolasCunha/tcc-framework, pull requests merged in 2020-08, with the labels that each got.

#5 Chore: General bugfixes
  src/main/java/com/br/framework/api/configurator/FrameConfigurator.java
  src/main/java/com/br/framework/bootstrap/SystemBootstrap.java
  src/main/java/com/br/framework/core/Frame.java
  src/main/java/com/br/framework/core/Handlebar.java
  src/main/java/com/br/framework/core/controller/PositionCalculator.java
  src/main/java/com/br/framework/core/database/query/QueryService.java
  src/main/java/com/br/framework/core/dbmetadata/MetadataLoader.java
  src/main/java/com/br/framework/core/dbmetadata/TableMetadata.java
  src/main/java/com/br/framework/core/enumerator/FrameComponent.java
  src/main/java/com/br/framework/core/factory/FrameFactory.java
  src/main/java/com/br/framework/core/factory/crud/CrudFactory.java
  src/main/java/com/br/framework/core/listener/ButtonListener.java
  src/main/java/com/br/framework/core/listener/TableListener.java
Labels: bug-fix

#7 Task: logging service; destroyable interface; service refactoring;
  build.gradle
  src/main/java/com/br/framework/api/configurator/FrameConfigurator.java
  src/main/java/com/br/framework/api/services/LoggingService.java
  src/main/java/com/br/framework/api/services/PropertiesServices.java
  src/main/java/com/br/framework/api/services/QueryService.java
  src/main/java/com/br/framework/bootstrap/SystemBootstrap.java
  src/main/java/com/br/framework/core/component/Frame.java
  src/main/java/com/br/framework/core/component/Handlebar.java
  src/main/java/com/br/framework/core/component/Table.java
  src/main/java/com/br/framework/core/component/interfaces/Destroyable.java
  src/main/java/com/br/framework/core/controller/PositionCalculator.java
  src/main/java/com/br/framework/core/database/connection/ConnectionPool.java
  src/main/java/com/br/framework/core/database/metadata/MetadataLoader.java
  src/main/java/com/br/framework/core/database/metadata/TableMetadata.java
  src/main/java/com/br/framework/core/database/query/QueryResult.java
  src/main/java/com/br/framework/core/factory/FrameFactory.java
  src/main/java/com/br/framework/core/factory/crud/CrudFactory.java
Labels: enhancement

#8 Task: create release workflow
  .github/workflows/create_release.yml
Labels: devops

#9 Task: create release workflow
  .github/workflows/create_release.yml
Labels: devops

#10 Task: create release workflow
  .github/workflows/create_release.yml
  package.json
Labels: devops

#11 Task: workflow
  .github/workflows/gradle.yml
Labels: devops

#12 chore: Update create_release.yml
  .github/workflows/create_release.yml
Labels: devops

#13 chore: Update create_release.yml
  .github/workflows/create_release.yml
Labels: devops

#14 Task: Workflow
  .github/workflows/create_release.yml
  .github/workflows/gradle.yml
Labels: devops

#15 Workflow
  .github/workflows/create_release.yml
Labels: devops

#16 Task: Update create_release.yml
  .github/workflows/create_release.yml
Labels: devops

#17 Update create_release.yml
  .github/workflows/create_release.yml
Labels: devops

#18 chore: fix gradle.yml
  .github/workflows/gradle.yml
Labels: devops

#19 chore: update readme
  README.md
Labels: documentation

#20 chore: gradle ci
  .github/workflows/gradle.yml
Labels: bug-fix, documentation

#21 chore: unfomatted timestamp
  .github/workflows/create_release.yml
Labels: devops

#22 chore: timestamp
  .github/workflows/create_release.yml
Labels: devops

#23 chore: update readme
  README.md
Labels: documentation

#24 chore: timestamp format
  .github/workflows/create_release.yml
Labels: devops

#25 Task: creation of handlebar and jbutton factories; general refactor;
  src/main/java/com/br/framework/api/configurator/FrameConfigurator.java
  src/main/java/com/br/framework/core/component/Handlebar.java
  src/main/java/com/br/framework/core/component/Table.java
  src/main/java/com/br/framework/core/controller/PositionCalculator.java
  src/main/java/com/br/framework/core/factory/component/CrudFactory.java
  src/main/java/com/br/framework/core/factory/component/FrameFactory.java
  src/main/java/com/br/framework/core/factory/component/HandlebarFactory.java
  src/main/java/com/br/framework/core/factory/swing/JButtonFactory.java
  src/main/java/com/br/framework/core/factory/swing/TableModelFactory.java
Labels: enhancement

#26 chore: update automatic release name
  .github/workflows/create_release.yml
Labels: devops

#27 Tasks: tests; bugfix; refactor.
  .github/workflows/gradle.yml
  build.gradle
  nbproject/project.properties
  src/main/java/com/br/framework/api/Framework.java
  src/main/java/com/br/framework/api/configurator/FrameConfigurator.java
  src/main/java/com/br/framework/bootstrap/SystemBootstrap.java
  src/main/java/com/br/framework/core/component/Frame.java
  src/main/java/com/br/framework/core/component/Handlebar.java
  src/main/java/com/br/framework/core/component/Table.java
  src/main/java/com/br/framework/core/controller/FrameController.java
  src/main/java/com/br/framework/core/controller/PositionCalculator.java
  src/main/java/com/br/framework/core/database/metadata/MetadataLoader.java
  src/main/java/com/br/framework/core/database/metadata/TableMetadata.java
  src/main/java/com/br/framework/core/factory/component/CrudFactory.java
  src/main/java/com/br/framework/core/factory/component/FrameFactory.java
  src/main/java/com/br/framework/core/factory/component/HandlebarFactory.java
  src/main/java/com/br/framework/core/factory/swing/JButtonFactory.java
  src/main/java/com/br/framework/core/factory/swing/JFrameFactory.java
  src/main/java/com/br/framework/core/factory/swing/TableModelFactory.java
  src/test/java/com/br/frame/FrameTest.java
Labels: bug-fix, test

#28 Task: typo
  src/test/java/com/br/frame/FrameTest.java
Labels: devops

#29 Task: singleton pattern
  src/main/java/com/br/framework/api/configurator/FrameConfigurator.java
  src/main/java/com/br/framework/bootstrap/SystemBootstrap.java
  src/main/java/com/br/framework/core/component/Table.java
  src/main/java/com/br/framework/core/controller/PositionCalculator.java
  src/main/java/com/br/framework/core/factory/component/CrudFactory.java
  src/main/java/com/br/framework/core/factory/component/FrameFactory.java
  src/main/java/com/br/framework/core/factory/component/HandlebarFactory.java
  src/main/java/com/br/framework/core/factory/swing/JButtonFactory.java
  src/main/java/com/br/framework/core/factory/swing/JFrameFactory.java
  src/main/java/com/br/framework/core/factory/swing/TableModelFactory.java
Labels: enhancement
